---
- name: Apps | Align putty.install
  ansible.builtin.include_tasks: ops/install-one.yml
  vars:
    pkg:
      name: putty.install
      version: "{{ choco_target_min_version_map[app_catalog_item.key] | default(acceptable_versions.applications.putty_install.min_version) }}"
      registry_patterns: "{{ app_catalog_item.registry_patterns | default(['putty']) }}"
      conflicts:
        - putty
        - putty.portable