---
- name: Apps | Align pycharm
  ansible.builtin.include_tasks: ops/install-one.yml
  vars:
    pkg:
      name: pycharm
      version: "{{ choco_target_min_version_map[app_catalog_item.key] | default(acceptable_versions.applications.pycharm.min_version) }}"
      conflicts:
        - pycharm-community
      registry_patterns: "{{ app_catalog_item.registry_patterns | default(['^PyCharm( Community| Professional)?']) }}"