define ROOT C:\Program Files\nxlog

#Machine specific variables
#define pipelineID       "Example_Windows"
#define group_ID         "Example_Group"
#define Location_ID      "Example Location"
#define Site_ID          "Example Site"
#end machine specific variables

Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%ROOT%\data\nxlog.log', 7);
     </Schedule>
</Extension>


<Extension gelfExt>
  Module xm_gelf
  # Avoid truncation of the short_message field to 64 characters.
  ShortMessageLength 65536
</Extension>
 ## Load required modules
<Extension json>
    Module      xm_json
</Extension>

## Input: Example using Windows Event Log
<Input eventlog_in>
        Module im_msvistalog
        PollInterval 30
        SavePos True
        ReadFromLast True
        #Exec $group_ID = %group_ID%;
        #Exec $Location_ID = %Location_ID%;
        #Exec $Site_ID = %Site_ID%;
        #Channel System
        <QueryXML>
            <QueryList>
                <Query Id='0' Path="System">
                    <Select Path="System">*[System/Level&lt;4]</Select>
                </Query>
                <Query Id='1' Path="Security">
                    <Select Path="Security">*[System[(EventID=4656 or EventID=4657
                    or EventID=4658 or EventID=4660
                    or EventID=4663 or EventID=4664
                    or EventID=4670 or EventID=4985
                    or EventID=4625 or EventID=4776
                    or EventID=4668 or EventID=4688
                    or EventID=5039 or EventID=5051
                    or EventID=4624)]]
                </Select>
                </Query>
                <Query Id='2' Path="Application">
                    <Select Path='Application'>*[System/Level&lt;4]</Select>
                </Query>
                <Query Id='3' Path="Setup">
                    <Select Path='Setup'>*[System/Level&lt;4]</Select>
                </Query>
            </QueryList>
        </QueryXML>
</Input>

## Output: Send GELF over HTTP to Graylog
<Output https_out>
    Module      om_http
    URL         https://graylog.example.com:47202/gelf
    ContentType application/json
    HTTPSAllowUntrusted TRUE
    <Exec>
       to_json();
       parse_json();
       if ($raw_event =~ /^\s*$/) drop();
       if ($message =~ /^\s*$/) drop();
       if ($host =~ /^\s*$/) drop();
       if ($SeverityValue < 3) drop();
       if ($EventID == 0) drop();
       rename_field("message", "short_message");
       delete($message); 
       delete($SourceModuleType); 
       delete($SourceModuleName);
       delete($Keywords);
       delete($Task);
       delete($OpcodeValue);
       delete($SRecordNumber);
       $host = $hostname;
       to_json();
    </Exec>
</Output>

<Output file>
    Module  om_file
    File    'C:\\Program Files\\nxlog\\data\\gelf_out.txt'
    <Exec>
       to_json();
       parse_json();
       if ($raw_event =~ /^\s*$/) drop();
       if ($message =~ /^\s*$/) drop();
       if ($host =~ /^\s*$/) drop();
       rename_field("message", "short_message");
       delete($message); 
       delete($SourceModuleType); 
       delete($SourceModuleName);
       delete($Keywords);
       delete($Task);
       delete($OpcodeValue);
       delete($SRecordNumber);
       $host = $hostname;
       to_json();
    </Exec>
</Output>


## Route: Connect input to output
<Route r>
    Path        eventlog_in => https_out
</Route>

#Optional local file for output troubleshooting
#<Route r-file>
#    Path        eventlog_in => file
#</Route>